language: node_js
node_js:
  - 11
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - npm run lint
  - npm run test
  - npm run build
deploy:
  provider: heroku
  app: the-react-boilerplate
  api_key:
    secure: d2a599ff-c5dc-4677-913f-eab85f23b6a7
  on:
    repo: theGirrafish/react-boilerplate
